### ISSUE TITLE
Issue on page /chapters/data/lists.html

### ISSUE THREAD

**Issue by haslam22** [cs3110/textbook#110]
Hi, thanks for the excellent course.

Section 3.1.2 (https://cs3110.github.io/textbook/chapters/data/lists.html#accessing-lists) has the following video which covers pattern matching in general (across lists, records, tuples): 

https://www.youtube.com/watch?v=AkrlDpHN_zE

And the written material for 3.1.2 covers:
* How to build a list
* Sum list recursive function
* Length of list recursive function
* Append two lists recursive function

Then in section 3.1.4 (https://cs3110.github.io/textbook/chapters/data/lists.html#pattern-matching-with-lists) we have a video covering what we already read through in section 3.1.2:

https://www.youtube.com/watch?v=sO9wxUxajS4

I feel like this video would be better placed in section 3.1.2.

**Comment by clarksmr** [comment]
Good point. Thank you!
