### ISSUE TITLE
Suggestion: remove `with module M = N` from the textbook?

### ISSUE THREAD

**Issue by favonia** [cs3110/textbook#123]
The `with module M = N` syntax sugar is very useful in practice (I have been using it), but I think this would only confuse students who just started learning OCaml. I would respectfully suggest that maybe we could remove `with module M = N` from the textbook Section 5.7, focusing only on `with type t = u`.

**Comment by clarksmr** [comment]
Thanks, but we give an assignment most semester in Cornell's CS 3110 where `with module` is essential. Our students who are learning OCaml seem to do just fine. So I'm not going to remove it.
