### ISSUE TITLE
Possibly missing line in definition of lambda calculus

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook#138]
The lambda calculus is currently defined as follows:

https://github.com/cs3110/textbook/blob/7b131977bcd587151bd700cd38ae83e72748a7fd/src/chapters/interp/substitution.md?plain=1#L668-L669

From what I understand, shouldn’t there also be an additional line for `x ::= <identifier>`?

**Comment by clarksmr** [comment]
I don't mind adding that, though I thought by that point it was clear from context.
