### ISSUE TITLE
Required background on AVL trees and 2-3 trees?

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook#139]
Exercise “standard library set” is as follows:

https://github.com/cs3110/textbook/blob/7b131977bcd587151bd700cd38ae83e72748a7fd/src/chapters/ds/exercises.md?plain=1#L240-L242

But the textbook only introduces red-black trees. More specifically, the following is _everything_ that the textbook has to say about 2-3 trees and AVL trees:

https://github.com/cs3110/textbook/blob/7b131977bcd587151bd700cd38ae83e72748a7fd/src/chapters/ds/rb.md?plain=1#L93-L101

https://github.com/cs3110/textbook/blob/7b131977bcd587151bd700cd38ae83e72748a7fd/src/chapters/ds/rb.md?plain=1#L302-L306

Is the reader assumed to already know about 2-3 trees and AVL trees from another source (e.g., another course)? Also, is it intended that the answer to the exercise has essentially been given in the main text?

**Comment by clarksmr** [comment]
Thank you!

I think this stems from a time several years ago when CS 3110 had an extensive assignment on 2-3 trees, so students would have been expected to know them from another source than the textbook. I agree that it's not a great exercise given what's actually in the textbook. I'll redact the exercise.
