### ISSUE TITLE
Incorrect reference to Stdlib.read_line

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook#140]
In section 7.1, we have the following sentence:

https://github.com/cs3110/textbook/blob/f20b28f70b19b06241a25c4431597d6af3b4e330/src/chapters/mut/refs.md?plain=1#L231-L233

This sentence claims that we have already seen the function `Stdlib.read_line`. But this function never appears (anywhere else) in the book. The only function named `read_line` that occurs in the book is `Lwt_io.read_line`, and even this function is only introduced in the next chapter (Chapter 8 on data structures).

**Comment by clarksmr** [comment]
Thank you! In assignments and labs before this topic (refs) in CS 3110, students have always seen `Stdlib.read_line`. But it's true that in the context of the textbook, the function is novel.
