### ISSUE TITLE
Issue on page /chapters/modules/toplevel.html

### ISSUE THREAD

**Issue by aw632** [cs3110/textbook#16]
From: https://edstem.org/us/courses/8213/discussion/654955

Issue message:

> I think I found a typo in the textbook, but can't figure out how to log into the Cornell GitHub to make a suggestion so I figured I'd post it here (bold and underlined). 

> Section 5.3.1 "That directive loads the bytecode found in mods.cmo, thus making a module named Mods available to be used. **It exactly** as if you had entered this code:"

Posting here as OP could not figure out how to make a github issue

**Comment by clarksmr** [comment]
Fixed in dbfa44
