### ISSUE TITLE
BST Map exercise

### ISSUE THREAD

**Issue by danil-braun** [cs3110/textbook#17]
> Exercise: binary search tree map [★★★]
> 
> Write a module `BstMap` that implements the `Map` module type using the a binary search tree type.

Was this exercise deliberately added before the chapter (8.3) on BST and BBST Map?

**Comment by clarksmr** [comment]
Yes, deliberate, because BSTs are assumed knowledge based on the prereqs for the class.  However, the exercise definitely could use more hints.  I added them in d01b83da235758b6766fe4524979f6f12ad73394.
