### ISSUE TITLE
Title of subsection 9.4.4 doesn’t match the content

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook#173]
Subsection 9.4.4 is named “An Implementation of SimPL in the Environment Model”. But it actually features an implementation for the lambda calculus instead of SimPL:

> #### 9.4.4. An Implementation of SimPL in the Environment Model
> You can download a complete implementation of the two semantics above: [lambda-env.zip](https://cs3110.github.io/textbook/code/lambda-env.zip) In `main.ml`, there is a definition named `scope` that you can use to switch between lexical and dynamic scope.
>
> #### 9.4.5. Evaluating Core OCaml in the Environment Model
> […]

(I don’t think the book even discusses the environment model for SimPL. It only does so indirectly by discussing it for Core OCaml at the end of section 9.4.)

PS.
[One of the linked videos][1] does actually feature an implementation of the environment model for SimPL. However,
- the code from the video doesn’t appear anywhere in the book (as far as I can tell),
- this video occurs at the beginning of 9.4, far away from 9.4.4.

[1]: https://www.youtube.com/watch?v=YZO-vQohBYA

**Comment by clarksmr** [comment]
Thanks!
