### ISSUE TITLE
Table on big-oh notation not displayed correctly

### ISSUE THREAD

**Issue by cionx** [cs3110/textbook#174]
The appendix on big-oh notation features the following table:

https://github.com/cs3110/textbook/blob/781cf6c354fd4cd5ffb484be09974ed01aea4072/src/chapters/appendix/bigoh.md?plain=1#L148-L155

This table isn’t displayed correctly. The current output looks as follows:

![table](https://github.com/cs3110/textbook/assets/7231796/7e9a2613-386f-47f3-aaaf-56ad85beea2f)

The following code should hopefully render correctly:

```markdown
 |           |  $N$  |  $N^2$  |  $N^3$  |  $2^N$   |
 |:----------|:-----:|:-------:|:-------:|:--------:| 
 |N=10       |< 1 sec|< 1 sec  |< 1 sec  | < 1 sec  |
 |N=100      |< 1 sec|< 1 sec  |  1 sec  |1017 years|
 |N=1,000    |< 1 sec|  1 sec  | 18 min  | very long|
 |N=10,000   |< 1 sec|  2 min  | 12 days | very long|
 |N=100,000  |< 1 sec|  3 hours| 32 years| very long|
 |N=1,000,000|  1 sec| 12 days |104 years| very long|
```

At least here on GitHub, this code renders as follows:

|           |  $N$  |  $N^2$  |  $N^3$  |  $2^N$   |
|:----------|:-----:|:-------:|:-------:|:--------:| 
|N=10       |< 1 sec|< 1 sec  |< 1 sec  | < 1 sec  |
|N=100      |< 1 sec|< 1 sec  |  1 sec  |1017 years|
|N=1,000    |< 1 sec|  1 sec  | 18 min  | very long|
|N=10,000   |< 1 sec|  2 min  | 12 days | very long|
|N=100,000  |< 1 sec|  3 hours| 32 years| very long|
|N=1,000,000|  1 sec| 12 days |104 years| very long|

(I’d personally also right-align all columns but the first, but that’s probably a matter of taste.)

**Comment by clarksmr** [comment]
Thanks!
