### ISSUE TITLE
Persistent arrays are not covered

### ISSUE THREAD

**Issue by clarksmr** [cs3110/textbook#181]
A new section in Chapter 8 should be added about persistent arrays, which are now covered in lecture.

**Comment by ethanuppal** [comment]
It would go [here](https://github.com/cs3110/textbook/tree/main/src/chapters/ds), after Red-Black Trees?

**Comment by ethanuppal** [comment]
I was wondering during class if in order for amortized $\mathcal{O}(1)$ cost per read operation there needs to be habitual copying of the array when version tree paths get "too long" or duplicate updates are performed?

**Comment by clarksmr** [comment]
Closed by 47c8a399267e8bd7d68d16963f9b8f266e9421ab
