### ISSUE TITLE
Live Code does not work

### ISSUE THREAD

**Issue by ethanuppal** [cs3110/textbook#182]
## Steps to Reproduce

1. Go to https://cs3110.github.io/textbook/chapters/preface/about.html
2. Press the following button:
    <img width="301" alt="Screenshot 2024-04-12 at 9 13 20 PM" src="https://github.com/cs3110/textbook/assets/113849268/2af634bc-7e89-4fe3-81a5-2358c2bdf91f">
3. Press the run button in the code example.

It will say `Waiting for kernel` and remove all CSS styling, as shown below:

<img width="814" alt="Screenshot 2024-04-12 at 9 14 28 PM" src="https://github.com/cs3110/textbook/assets/113849268/1b481b76-ee71-414e-9931-031a40152b62">

**Comment by clarksmr** [comment]
Hm, I can't recreate.

<img width="814" alt="Screenshot 2024-04-12 at 10 43 56 PM" src="https://github.com/cs3110/textbook/assets/6808228/a4a735ce-9362-4f70-be86-bc4ed2e3e032">

**Comment by ethanuppal** [comment]
Maybe [this](https://github.com/ocsigen/js_of_ocaml) would be worth looking into? Or maybe there is a wasm target for the OCaml compiler?
