### ISSUE TITLE
`within` in exercise "better e" (chapter 8)

### ISSUE THREAD

**Issue by vitalydolgov** [cs3110/textbook#29]
I just wonder if I completely misunderstood the improved formula for difference, or maybe I'm missing some of its preconditions, but

`\frac{|a - b|}{\frac{|a| + |b|}{2} + 1}`

implemented as 

`let eps a b = abs (a -. b) /. ((abs a +. abs b) /. 2. +. 1.)` returns very small value for
```
# eps 21991. 22011.;;
- : float = 0.000909008271975275
```
So using it to calculate which of the value in sequence `total` falls within some `eps` forces search to stop earlier, than with simple `abs (a -. b)`.

Could you please check the formula?

P.S. I found that replacing "plus" with "minus" in denominator gives better results, but I'm not sure if it's correct, as I don't know the source of the method.

**Comment by clarksmr** [comment]
That's a great question. TBH I don't remember where that formula came from either!  It's possible it's from some old course notes or a TA or something.  And searching around for it, I'm not immediately seeing that formula show up in any sources on floating point comparison.

I'm thinking of replacing that formula with a standard formula for relative distance.  For example, what the Boost library uses: https://www.boost.org/doc/libs/1_77_0/libs/math/doc/html/math_toolkit/float_comparison.html

What do you think?

**Comment by vitalydolgov** [comment]
Yeah, this is good idea, it would also be great to add some reference to Wikipedia/MathWorld or even some implementation. I like the fact that textbook exercises interwoven with some "external" ideas, I think this a great way to introduce them for further studies and to show how they are used in production.
