### ISSUE TITLE
Issue on page /chapters/hop/pipelining.html

### ISSUE THREAD

**Issue by ColMcp** [cs3110/textbook#36]
I believe the Python definition of `sum_sq` is incorrect: the for-loop executes with values from 0 to n-1. Shouldn't it be `for i in range(1, n+1):`  since the `stop` value for a range is non-inclusive?

Thank you for making this book and its videos available - it has improved my understanding of OCaml, and functional programming in general, immensely.

**Comment by clarksmr** [comment]
Right — thanks!
