### ISSUE TITLE
The italic code may be incorrect , at least intuitively not being aligned with the UnMemoized counterpart

### ISSUE THREAD

**Issue by AronSwan** [cs3110/textbook#37]
module Memoized = struct
  (* This version memoizes the optimal fun value for each tree node. It
     also remembers the best invite list. Each tree node has the name of
     the employee as a string. *)
  type tree =
    | Empty
    | Node of
        int * string * tree * tree * (int * string list) option ref

  let rec party t : int * string list =
    match t with
    | Empty -> (0, [])
    | Node (v, name, left, right, memo) -> (
        match !memo with
        | Some result -> result
        | None ->
            let infun, innames = party_in t in
            let outfun, outnames = party_out t in
            let result =
              if infun > outfun then _**(v + infun, name :: innames)**_
              else (outfun, outnames)
            in
            memo := Some result;
            result)

  and party_in t =
    match t with
    | Empty -> (0, [])
    | Node (v, name, l, r, _) ->
        let lfun, lnames = party_out l and rfun, rnames = party_out r in
        (v + lfun + rfun, name :: lnames @ rnames)

  and party_out t =
    match t with
    | Empty -> (0, [])
    | Node (v, _, l, r, _) ->
        let lfun, lnames = party l and rfun, rnames = party r in
        (lfun + rfun, lnames @ rnames)

_end_

**Comment by clarksmr** [comment]
@jnfoster I think you added that code — maybe you could take a look?

**Comment by jnfoster** [comment]
Looks like comes from before my time on the hill, unless I contributed this example during my interview in April 2009 :-)
https://www.cs.cornell.edu/courses/cs3110/2009sp/lectures/lec23.html

Happy to look. To make sure I understand, the complaint is that the memoized and unmemoized versions of the function don't closely resemble each other?

**Comment by clarksmr** [comment]
(I guess I meant you added it into the current textbook in 2019 spring when you were teaching the course.)

**Comment by jnfoster** [comment]
No good deed goes unpunished...

**Comment by minungkuo** [comment]
I also notice this problem. In module Memoized the function party should not add root node value to to the total fun value or insert root node's name to invite list because it has been recorded by  previous recursively function call. And I think simply replace `(v + infun, name :: innames)` with `(infun, innames)` will reslove this problem.
