### ISSUE TITLE
Issue on page /chapters/ds/hash_tables.html

### ISSUE THREAD

**Issue by calciiium** [cs3110/textbook#61]
In 8.1.6, I found a small typo: "To support clients who want to hash such structures, Hashtble provides another function hash_param which can be configured to examine more nodes." It should be Hashtbl not Hashtble.

**Comment by jnfoster** [comment]
Actually, I think Hashtbl is right. See here: https://ocaml.org/api/Hashtbl.html

**Comment by calciiium** [comment]
Yes I realized this right after creating this issue. Sorry!

**Comment by calciiium** [comment]
Wait... I'm sorry but should it be Hashtbl not Hashtble...?
