### ISSUE TITLE
Issue on page /chapters/interp/exercises.html

### ISSUE THREAD

**Issue by dragon-girl88** [cs3110/textbook#70]
The exercise to parse simpl expressions seems to not be updated to work with a dune build system.
![Uploading Screen Shot 2022-05-07 at 7.49.44 PM.png…]()
 
They should instead say Interp.main.parse "22"
<img width="352" alt="Screen Shot 2022-05-07 at 7 50 28 PM" src="https://user-images.githubusercontent.com/69407676/167275809-72f0611f-cda7-4eaa-a159-ee10ef891d4b.png">

**Comment by jnfoster** [comment]
Thanks. Will fix.
