### ISSUE TITLE
Issue on page /chapters/basics/compiling.html

### ISSUE THREAD

**Issue by mjn298** [cs3110/textbook#80]
The current version of dune requires a file in the top-level directory (in this case, would just be `./hello-world`) called `dune-project` with the following 

`(lang dune 3.0)` 

I think this file used to be automatically generated if absent, now it requires explicit creation.

**Comment by jnfoster** [comment]
@clarksmr can I leave this for you? Seems like we either want to pin the version, or freshen the install instructions.

**Comment by clarksmr** [comment]
Yes, this appears to be because Dune was at version 2 when the Fall 2021 version of the textbook was released, but now Dune is at version 3.  I'll look into upgrading the textbook to use version 3.

**Comment by clarksmr** [comment]
4e36ad6 will fix this when published.  That commit adds instructions for creating `dune-project` manually.  Thanks!
