### ISSUE TITLE
Issue on page /chapters/basics/compiling.html

### ISSUE THREAD

**Issue by wbwqq** [cs3110/textbook#84]
`dune build hello.exe`

Doesn't work. This is the error message: 

```
Error: I cannot find the root of the current workspace/project.
If you would like to create a new dune project, you can type: 

    dune init project NAME

Otherwise, please make sure to run dune inside an existing project or
workspace. For more information about how dune identifies the root of the
current workspace/project, please refer to
https://dune.readthedocs.io/en/stable/usage.html#finding-the-root
```

It seems that the manual doesn't mention the fact that a dune project needs to be initialized.

**Comment by wbwqq** [comment]
When I try to run `dune build hello.exe`, I get the same error message even after running `dune init project hello`. Here is the list of files in the directory:
```
_build/
hello/
dune
dune_project
hello.ml
```

**Comment by clarksmr** [comment]
Probably the same root cause as #80:  the Dune version has changed since the last textbook release.  I'm looking into it.

**Comment by wbwqq** [comment]
Thanks! In the meantime if anyone has a similar issue, I made a small bash script as a workaround:

```bash
file=$1
filename=${file%.*}
rm -rf $filename-ocaml/
mkdir $filename-ocaml
cp $file $filename-ocaml/$file
cd $filename-ocaml
ocamlc -o $filename.byte $file
cd ..
./$filename-ocaml/$filename.byte
```

**Comment by clarksmr** [comment]
4e36ad6 will fix this when published.

Note that there's a simpler solution than the script above:  just manually create a `dune-project` file.  No need for the entire directory infrastructure that `dune init project` creates.
